In [2]:
import sqlite3
import pandas as pd

In [3]:
c = sqlite3.connect('position_tracker.db')
sql = '''
select * from position_table
'''
df = pd.read_sql(sql, c)
c.close()
df

,Month,Employee #,Filled Position Description,Filled FTE Percent,Current Salary
0,April-17,3504.0,ASST CITY ATTY,1.0,143627.0
1,April-17,2114.0,LITIGATION ASST 1,1.0,67232.0
2,April-17,1351.0,CLERK-TYP 2,1.0,48896.0
3,April-17,3630.0,ASST CITY ATTY,1.0,144933.0
4,April-17,3074.0,SECRETARY 3-LEGAL,1.0,59614.0
5,April-17,2963.0,ATTY CITY,1.0,160114.0
6,April-17,3669.0,ASST CITY ATTY,1.0,77420.0
7,April-17,1121.0,LEGAL OFFICE ASST,1.0,48065.0
8,April-17,2665.0,SECRETARY 2-LEGAL,1.0,54038.0
9,April-17,1381.0,ASST CITY ATTY,1.0,84205.0
10,April-17,1215.0,ORD REVISIONS SPEC,1.0,60505.0
11,April-17,2320.0,ASST CITY ATTY,1.0,144933.0
12,April-17,1288.0,DEPUTY CITY ATTY,1.0,140171.0
13,April-17,1249.0,SECRETARY 2-LEGAL,1.0,49623.0
14,April-17,3826.0,ASST CITY ATTY,1.0,112182.0
15,April-17,2708.0,ASST CITY ATTY,1.0,110294.0
16,April-17,4087.0,ASST CITY ATTY,1.0,144933.0
17,April-17,9053.0,ASST CITY ATTY,1.0,65755.0
18,April-17,4118.0,SECRETARY 2-LEGAL,1.0,54038.0
19,April-17,1159.0,ASST CITY ATTY,1.0,88933.0
20,April-17,1032.0,ALDERMAN,1.0,12883.0
21,April-17,4130.0,COUNCIL PRESIDENT,1.0,15676.0
22,April-17,1402.0,COUNCIL PRES PRO TEM-19,1.0,13898.0
23,April-17,3739.0,ADMIN ASST,1.0,62213.0
24,April-17,4110.0,SECRETARY 1,1.0,54073.0
25,April-17,9084.0,SECY TO MAYOR,1.0,50837.0
26,April-17,9029.0,MAYORAL OFF CLK,1.0,45216.0
27,April-17,9227.0,MAYORAL OFF CLK,1.0,45216.0
28,April-17,1128.0,DEPUTY MAYOR 2,1.0,117679.0
29,April-17,5757.0,DEPUTY MAYOR 2,1.0,95075.0
...,...,...,...,...,...
71263,September 2018,NaN,None,NaN,NaN
71264,September-18,2853.0,FIRE LIEUTENANT,1.0,93415.0
71265,September 2018,NaN,None,NaN,NaN
71266,September 2018,NaN,None,NaN,NaN
71267,September 2018,NaN,None,NaN,NaN
71268,September 2018,NaN,None,NaN,NaN
71269,September-18,11154.0,FIREFIGHTER,1.0,55586.0
71270,September-18,11153.0,FIREFIGHTER,1.0,55586.0
71271,September-18,11152.0,FIREFIGHTER,1.0,55586.0
71272,September-18,11151.0,FIREFIGHTER,1.0,55586.0
71273,September-18,11150.0,FIREFIGHTER,1.0,55586.0
71274,September-18,11149.0,FIREFIGHTER,1.0,55586.0
71275,September-18,11148.0,FIREFIGHTER,1.0,55586.0
71276,September-18,11147.0,FIREFIGHTER,1.0,55586.0
71277,September-18,11146.0,FIREFIGHTER,1.0,55586.0
71278,September-18,2160.0,PROGRAM ASST 2,1.0,55752.0
71279,September-18,11496.0,POLICE OFFICER,1.0,50415.0
71280,September-18,10705.0,POLICE OFFICER,1.0,56058.0
71281,September-18,10706.0,POLICE OFFICER,1.0,56058.0
71282,September-18,10707.0,POLICE OFFICER,1.0,56058.0
71283,September-18,10708.0,POLICE OFFICER,1.0,56058.0
71284,September-18,10709.0,POLICE OFFICER,1.0,56058.0
71285,September-18,10710.0,POLICE OFFICER,1.0,56058.0
71286,September-18,10711.0,POLICE OFFICER,1.0,56058.0
71287,September-18,11786.0,LIBRARIAN 1-PT,0.7,37584.0
71288,September-18,11772.0,LIBRARIAN 1-PT,0.6,32185.0
71289,September-18,7119.0,LIB COMP TECH,1.0,44931.0
71290,September-18,11606.0,DIR OF TRANSPORT,1.0,155000.0
71291,September-18,11614.0,ACCT TECH 1-20,1.0,49726.0
71292,September-18,10645.0,ADMIN CLK 1 CONF,1.0,43682.0

In [5]:
c = sqlite3.connect('position_tracker.db')
sql = '''
select distinct "Filled Position Description" from position_table
'''
df = pd.read_sql(sql, c)
c.close()
df

      Filled Position Description
0                  ASST CITY ATTY
1               LITIGATION ASST 1
2                     CLERK-TYP 2
3               SECRETARY 3-LEGAL
4                       ATTY CITY
5               LEGAL OFFICE ASST
6               SECRETARY 2-LEGAL
7              ORD REVISIONS SPEC
8                DEPUTY CITY ATTY
9                        ALDERMAN
10              COUNCIL PRESIDENT
11        COUNCIL PRES PRO TEM-19
12                     ADMIN ASST
13                    SECRETARY 1
14                  SECY TO MAYOR
15                MAYORAL OFF CLK
16                 DEPUTY MAYOR 2
17                          MAYOR
18           MAYOR'S OFF ADMIN CO
19                         AA MGR
20                AFF ACTION SPEC
21                          CCS 2
22                 PROGRAM ASST 1
23                  DR & SP COORD
24                  M.T. DIRECTOR
25            M.T. ASSOC DIRECTOR
26               COM DEV PROG MGR
27           CHILD CARE ASST COOR
28      CHILD CARE PROG SPEC 1-18
29                 PROGRAM ASST 2
...                           ...
1131            PO RECORDS CUSTOD
1132           TRAINING CTR COORD
1133             DIR OF TRANSPORT
1134             ADMIN CLK 1 CONF
1135              CITY TRAFF ENGR
1136           SUSTAIN PROG COORD
1137               LIBRARIAN 1-PT
1138         GRANTS ADMIN 2-18-PT
1139               COM DEV SPEC 2
1140        WATER UTIL PUB INFO 2
1141     DIGITAL MEDIA SPECIALIST
1142                 COUNCIL PRES
1143         COUNCIL PRES PRO TEM
1144             COM DEV PROG NGR
1145           COM DEV PROG COORD
1146                    ADMIN CLK
1147         COMP OFF ADMIN SERVS
1148           HSG ADMIN COORD-18
1149                  PROG ASST 2
1150             PKG EQUIP TECH 2
1151                   POLICE SGT
1152      PROPERTY CODE INSP 2-16
1153          WATER RES SPEC 2-18
1154                MUNI CLK 1-20
1155  DIGITAL MEDIA SUPERVISOR-18
1156        SAFETY COORDINATOR-18
1157         M.T. COM.REL.SUPV-18
1158        M.T. GIFT SHOP MGR-18
1159        ST VENDING MONITOR-16
1160          COMM CO LEG ANAL-18

[1161 rows x 1 columns]

In [ ]:
c = sqlite3.connect('position_tracker.db')
sql = '''
select distinct "Filled Position Description" from position_table
'''
df = pd.read_sql(sql, c)
c.close()
df